### ISSUE TITLE
changing preset via double-click has weird results

### ISSUE THREAD

**Issue by underwatercolor** [Openlights/firemix#41]
Sorry for the rambling bug report....

If you "Pause" the playlist during a transition, then double-click a different preset, I think it should stop the transition and cut to the preset you asked for. It might do this currently, but the UI gets left behind / still appears to be mid-transition.

It would be nice if the transition bar showed the "progress until transition" when not in a transition.

**Comment by craftyjon** [comment]
double-click after first opening firemix doesn't have any effect.

**Comment by craftyjon** [comment]
Pausing during a transition and then double-clicking has some weird results.  Should just cut to what you double click to

**Comment by craftyjon** [comment]
Mostly fixed now?
