### ISSUE TITLE
display current preset more prominently

### ISSUE THREAD

**Issue by underwatercolor** [Openlights/firemix#42]
In Firemix, it's important to know which preset's parameters are currently displayed / editable.

In the playlist, one preset is highlighted in blue and one in orange. These may not even be on screen, and it's easy to forget which color is more relevant right now.

When editing preset parameters, there can be only one active preset, which I guess is the orange one.

I'd like this to be less confusing somehow, but I'm not sure what the best way is. Modifying some text somewhere to tell the user what they are transitioning from and to sounds nice. Maybe where it says Preset Parameters it could also say which preset it is.

**Comment by craftyjon** [comment]
Current preset is now displayed in parameter window

**Comment by craftyjon** [comment]
Fixed in ec7e5e4
