### ISSUE TITLE
Fix all transitions to allow progress to go backwards

### ISSUE THREAD

**Issue by craftyjon** [Openlights/firemix#71]
Many of the transitions assume progress will only go forwards.
Now that we have scrubbing, need to fix this.
Fuzz already fixed as a test.

**Comment by craftyjon** [comment]
Easy way to test:

1. Select transition to test
2. Pause playback
3. Jump to a preset that looks different from the next (I use "spiral fire"/"spiral ice")
4. Scrub the transition forward, observe, then scrub backwards and see if it goes back to the original preset or gets "stuck" at whatever the most forward point was

**Comment by nyarasha** [comment]
Created solid color preset to make testing this easier.

**Comment by craftyjon** [comment]
Fixed
