### ISSUE TITLE
Playlist save error on quit

### ISSUE THREAD

**Issue by tibbon** [Openlights/firemix#94]
Under Mac OS 10.12, when I quit the program I see the following in my terminal:

```
(venv) ➜  firemix git:(master) ✗ python firemix.py firefly2015
^CERROR:firemix:Ignoring exception during shutdown request
Traceback (most recent call last):
  File "firemix.py", line 32, in call_ignoring_exceptions
    func()
  File "/Users/dfisher/code/openlights/firemix/firemix_app.py", line 82, in stop
    self.playlist.save()
  File "/Users/dfisher/code/openlights/firemix/lib/playlist.py", line 331, in save
    self.data['playlist'] = playlist
AttributeError: 'Playlist' object has no attribute 'data'
```

**Comment by zbenjamin** [comment]
Was this with an empty playlist? The `Playlist` object seems to do a lot of initialization in `open` that should be moved to its `__init__` method, instead.

**Comment by tibbon** [comment]
Yea, I think the problem is that there's no last_playlist, and if when
starting the app you don't manually pass in `--playlist default` then the
first time it runs it can't find it.
